services:
  php-game-manager-db:
    image: "mysql:8"
    container_name: "php-game-manager-db"
    restart: "unless-stopped"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - ./database/db_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d